[package]
name = "lucas"
version = "0.1.0"
edition = "2021"
authors = ["Lucas <lucas@devlucas.page>"]
description = "A scripting language in Portuguese"
license = "MIT"

[dependencies]
lazy_static = "1.4"
colored = "2.1"